version: '2'
services:
  pustaka-app:
    image: pustaka
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://pustaka-mariadb:3306/pustaka
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  pustaka-mariadb:
    extends:
      file: mariadb.yml
      service: pustaka-mariadb
